% function initObliFig(h_fig)
% 初始化斜激波的图窗
%% beta-Ma1
% 创建图窗
fig_obliq_beta = axes('Parent',h_fig,...
                        'Units','normalized',...
                        'Position',[0.06, 0.08, 0.6, 0.75],...
                        'XTick',[],...
                        'YTick',[],...
                        'Visible','off',...
                        'tag','Obli_beta',...
                        'Box','On');
setappdata(h_fig,'fig_obliq_beta',fig_obliq_beta);


%% Ma2-Ma1
fig_obliq_ma2 = axes('Parent',h_fig,...
                        'Units','normalized',...
                        'Position',[0.06, 0.08, 0.6, 0.75],...
                        'XTick',[],...
                        'YTick',[],...
                        'Visible','off',...
                        'tag','Obli_ma2',...
                        'Box','On');
setappdata(h_fig,'fig_obliq_ma2',fig_obliq_ma2);

%% RD-Ma1
% 创建图窗
fig_obliq_r2r1 = axes('Parent',h_fig,...
                        'Units','normalized',...
                        'Position',[0.06, 0.08, 0.6, 0.75],...
                        'XTick',[],...
                        'YTick',[],...
                        'Visible','off',...
                        'tag','Obli_r2r1',...
                        'Box','On');
setappdata(h_fig,'fig_obliq_r2r1',fig_obliq_r2r1);

%% RP-Ma1
% 创建图窗
fig_obliq_p2p1 = axes('Parent',h_fig,...
                        'Units','normalized',...
                        'Position',[0.06, 0.08, 0.6, 0.75],...
                        'XTick',[],...
                        'YTick',[],...
                        'Visible','off',...
                        'tag','Obli_p2p1',...
                        'Box','On');
setappdata(h_fig,'fig_obliq_p2p1',fig_obliq_p2p1);

%% RT-Ma1
% 创建图窗
fig_obliq_t2t1 = axes('Parent',h_fig,...
                        'Units','normalized',...
                        'Position',[0.06, 0.08, 0.6, 0.75],...
                        'XTick',[],...
                        'YTick',[],...
                        'Visible','off',...
                        'tag','Obli_t2t1',...
                        'Box','On');
setappdata(h_fig,'fig_obliq_t2t1',fig_obliq_t2t1);
% end

