close all;
addpath(genpath('.'));      % 添加子文件路径以查找回调函数

% 窗体设置
h_fig = figure('Name','空气动力学常用参数计算查询系统',...
    'MenuBar','None',...
    'NumberTitle','off',...
    'ToolBar','None',...
    'Units','normalized',...
    'Position',[0.05 0.05 0.64 0.85]);

% 创建菜单项
h_menu = uimenu(h_fig,'label','编辑');
h_submenu1 = uimenu(h_menu,'label','保存图片',...
                    'callback','');
h_submenu2 = uimenu(h_menu,'label','导入数据',...
                    'callback','');

% 创建名称
h_text=uicontrol(h_fig,'style','text',...
            'unit','normalized',...
            'position',[0.35,0.93,0.35,0.05],...
            'horizontal','center',...
            'FontName','隶书',...
            'FontSize',17,...
            'string','空气动力学常用参数计算查询系统');

% 创建图窗
ax_fig = axes('Parent',h_fig,...
    'Units','normalized',...
    'Position',[0.06, 0.08, 0.6, 0.75],...
    'XTick',[],...
    'YTick',[],...
    'Box','On');
setappdata(h_fig,'ax_fig',ax_fig);

% 创建下拉菜单
pum = uicontrol('Style','popupmenu',...
    'Parent',h_fig,...
    'String',{'正激波','斜激波'},...
    'FontSize',10,...
    'Units','normalized',...
    'Position',[0.75, 0.65, 0.18, 0.2]);
setappdata(h_fig,'pum',pum);

% 创建按钮
btn1 = uicontrol('Style','pushbutton',...
    'Parent',h_fig,...
    'String','功能1',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.78,0.4,0.18,0.1],...
    'Callback',{@callback_btn1,h_fig});
setappdata(h_fig,'btn1',btn1)

btn2 = uicontrol('Style','pushbutton',...
    'Parent',h_fig,...
    'String','功能2',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.78,0.1,0.18,0.1],...
    'Callback',{@callback_btn2,h_fig});
setappdata(h_fig,'btn2',btn2)

btn3 = uicontrol('Style','pushbutton',...
    'Parent',h_fig,...
    'String','功能3',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.78,0.25,0.18,0.1],...
    'Callback',{@callback_btn3,h_fig});
setappdata(h_fig,'btn3',btn3)