function info_cell = info()
% 关于信息
info_cell = {'Application Name: 空气动力学激波参数计算系统（APQS）';...
            'Author Name: 张卓立 王慕尧';...
            'University: 西北工业大学';...
            'Summary: 用于快捷查询正斜激波相关数值并绘图可视化'};
end

