function info_cell = info()
% 关于信息
info_cell = {'Application Name: 空气动力学常用参数计算查询系统（APQS）';...
            'Author Name: 张卓立 王慕尧';...
            'University: Northwestern Polytechnical University';...
            'Summary: 用于快捷查询正斜激波相关数值并绘图可视化'};
end

