%-----------默认Ma2-Ma1为初始图像-------------%
% 由绘图按钮btn1调用初始化，可获得句柄h_fig
%% 导入图窗句柄
fig_ma2 = getappdata(h_fig,'fig_ma2');
fig_r2r1 = getappdata(h_fig,'fig_r2r1');
fig_p2p1 = getappdata(h_fig,'fig_p2p1');
fig_t2t1 = getappdata(h_fig,'fig_t2t1');

%% Ma2-Ma1
% fig_ma2 = axes('Parent',h_fig,...
%                         'Units','normalized',...
%                         'Position',[0.06, 0.08, 0.6, 0.75],...
%                         'XTick',[],...
%                         'YTick',[],...
%                         'tag','Nor_ma2',...
%                         'Box','On');
% setappdata(h_fig,'fig_ma2',fig_ma2);

plot(fig_ma2,1:0.01:30,normalm1_m2(1:0.01:30));
grid(fig_ma2,'on')
grid(fig_ma2,'minor')
title(fig_ma2,'Ma2随Ma1变化规律');
xlabel(fig_ma2,'Ma1');
ylabel(fig_ma2,'Ma2');

%% RD-Ma1
% fig_r2r1 = axes('Parent',h_fig,...
%                         'Units','normalized',...
%                         'Position',[0.06, 0.08, 0.6, 0.75],...
%                         'XTick',[],...
%                         'YTick',[],...
%                         'tag','Nor_r2r1',...
%                         'Box','On');
% setappdata(h_fig,'fig_r2r1',fig_r2r1);

plot(fig_r2r1,1:0.01:30,normalm1_RD(1:0.01:30));
grid(fig_r2r1,'on')
grid(fig_r2r1,'minor')
title(fig_r2r1,'ρ2/ρ1随Ma1变化规律');
xlabel(fig_r2r1,'Ma1');
ylabel(fig_r2r1,'ρ2/ρ1');

%% RP-Ma1
% fig_p2p1 = axes('Parent',h_fig,...
%                         'Units','normalized',...
%                         'Position',[0.06, 0.08, 0.6, 0.75],...
%                         'XTick',[],...
%                         'YTick',[],...
%                         'tag','Nor_p2p1',...
%                         'Box','On');
% setappdata(h_fig,'fig_p2p1',fig_p2p1);

plot(fig_p2p1,1:0.01:30,normalm1_RP(1:0.01:30));
grid(fig_p2p1,'on')
grid(fig_p2p1,'minor')
title(fig_p2p1,'P2/P1随Ma1变化规律');
xlabel(fig_p2p1,'Ma1');
ylabel(fig_p2p1,'P2/P1');

%% RT-Ma1
% fig_t2t1 = axes('Parent',h_fig,...
%                         'Units','normalized',...
%                         'Position',[0.06, 0.08, 0.6, 0.75],...
%                         'XTick',[],...
%                         'YTick',[],...
%                         'tag','Nor_t2t1',...
%                         'Box','On');
% setappdata(h_fig,'fig_t2t1',fig_t2t1);

plot(fig_t2t1,1:0.01:30,normalm1_RT(1:0.01:30));
grid(fig_t2t1,'on')
grid(fig_t2t1,'minor')
title(fig_t2t1,'T2/T1随Ma1变化规律');
xlabel(fig_t2t1,'Ma1');
ylabel(fig_t2t1,'T2/T1');

%% 初始化可见性
callback_switchFig(h_fig)